server:
  # 端口配置
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
    # session超时时间
    session:
      timeout: 30m
spring:
  application:
    # 应用名称
    name: WareCase
  # 配置json解析，当属性值为null时不序列化
  jackson:
    default-property-inclusion: non_null
  # 配置连接池
  datasource:
    # 数据连接池类型
    type: com.zaxxer.hikari.HikariDataSource
    # 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接地址
    url: jdbc:mysql://8019team14.mysql.database.azure.com:3306/csc8019?useUnicode=true&characterEncoding=utf8&useSSL=false
    # 用户名
    username: T14
    # 密码
    password: CSC8019!
    # 连接池配置
    hikari:
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 120000
      connection-timeout: 30000
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 配置aop
  aop:
    proxy-target-class: true


# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.warecase.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:com/warecase/mapper/*Mapper.xml
  configuration:
    # 开启驼峰命名
    mapUnderscoreToCamelCase: true
    # 打印sql语句


logging:
  # 配置日志级别为DEBUG
  level:
    com.warecase.mapper: debug

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: dasdkjfds
  # 令牌有效期（默认30分钟）
  expireTime: 30
